# Events: what triggers the automation (workflow)
# Workflows: contain all jobs
# Jobs: use the actions to perform the tasks
# Actions: executable commands (pre-buil or manual buld)

name: Test ASP backend
on: [push]
jobs:
  run_unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet version
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Display dotnet version
        run: dotnet test
